apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/frontend.yaml
  - manifests/backend.yaml
  - manifests/ingress.yaml
  - manifests/volumes.yaml
  - manifests/cronjob-backup.yaml
images:
  - name: zanaad/todo-app
    newName: gcr.io/dwk-gke-457320/todo-app
  - name: zanaad/todo-backend
    newName: gcr.io/dwk-gke-457320/todo-backend

