apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "0 0 * * *" # Every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: google/cloud-sdk:slim
            env:
              - name: PGHOST
                value: "postgres-svc.todo.svc.cluster.local"

              - name: PGDATABASE
                value: "tododb"

              - name: PGUSER
                value: "todouser"

              - name: PGPASSWORD
                value: "todopassword"
              - name: BUCKET_NAME
                value: "zana-db-backups-2025"
            volumeMounts:
              - name: gcp-key
                mountPath: /secrets
                readOnly: true
            command:
              - /bin/bash
              - -c
              - |
                export GOOGLE_APPLICATION_CREDENTIALS="/secrets/key.json"
                BACKUP_FILE="backup-$(date +%F).sql"
                echo "Starting pg_dump..."
                pg_dump -h $PGHOST -U $PGUSER $PGDATABASE > $BACKUP_FILE
                echo "Authenticating to GCP..."
                gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
                echo "Uploading backup..."
                gsutil cp $BACKUP_FILE gs://$BUCKET_NAME/
          restartPolicy: OnFailure
          volumes:
          - name: gcp-key
            secret:
              secretName: gcp-key-secret
