name: Deploy Todo App

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_LOCATION: europe-west3
  FRONTEND_IMAGE: todo-app
  BRANCH: ${{ github.ref_name }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_LOCATION }}'
          project_id: '${{ env.PROJECT_ID }}'

      - name: Build and Push Frontend Image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA ./frontend
          docker push gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA

      - name: Deploy with Kustomize
        run: |
          if [[ "$BRANCH" == "master" ]]; then
            NAMESPACE="todo"
          else
            NAMESPACE="${BRANCH}"
          fi

          echo "Deploying to namespace: $NAMESPACE"

          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE
          # Update kustomize namespace
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image zanaad/todo-app=gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA
          kustomize edit set image zanaad/todo-backend=gcr.io/$PROJECT_ID/$BACKEND_IMAGE:$BRANCH-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment todo-app
          kubectl rollout status deployment todo-backend
          kubectl get services
